### ISSUE TITLE
Peer review Lab2 - Pietro Noto s301332

### ISSUE THREAD

**Issue by PietroNoto** [CarachinoAlessio/computational_intelligence#4]
<h1>Overview</h1>

<p>
Your algorithm makes use of the Genetic approach and provides more randomness and few other edits in respect to the vanilla version. Set cover problem has been solved for the whole set of N = {5, 10, 20, 50, 100, 500, 1000}.
The code looks quite clear and you've made good use of the Python language but I'd have appreciated comments in the most "personal" functional parts.

<h1>Your edits</h1>

<p>
In the evolution phase you added more randomness to the algorith, by drawing a random number and, in respect to the outcome, you considered 3 possible cases in order to either mutate a gene or make a crossover.
Also, the "randomness" influencing the aforementioned behaviour changes in respect to the number of generations, in order to enhance variability if the computation requires more generations.
In the mutation and crossover functions you added a random gene added picked from the "gene pool" added to the offspring. The mutation_shut_down function removes from a genome the gene that - assuming the genome is a solution - would cause the element count in the set of lists to be the highest, so sub-optimal. 
I appreciated the stopping condition employed (improvement from previous best solution, fitness depending also on population size) because it reminds me gradient descent for deep learning tasks. 
</p>

<h1>Performance analysis</h1>

<p>
Overall, the algorithm looks pretty efficient and provides good and fast results: it takes around 5secs to complete the problem for 5 < N < 100, and around 5min40sec to solve N = 500 on my machine.
I confirm your results, which are shown below:
    * N = 5, OS = 5 -> w = 5, gen = 200
    * N = 10, OS = 9 -> w = 10, gen = 400
    * N = 20, OS = 15 -> w = 27, gen = 400
    * N = 50, OS = 30 -> w = 77, gen = 400
    * N = 100, OS = 90 -> w = 182, gen = 400
    * N = 500, OS = 200 -> w = 1328, gen = 1000

I tweaked the values of OFFSPRING_SIZE and managed to improve your algorithm, have a look:
    * N = 5, OS = 10 -> w = 5, gen = 200
    * N = 10, OS = 20 -> w = 10, gen = 400
    * IMPROVED: N = 20, OS = 30 -> w = 24, gen = 400
    * N = 50, OS = 60 -> w = 77, gen = 400
    * IMPROVED: N = 100, OS = 180 -> w = 178, gen = 400
    * SLIGHTLY WORSE: N = 500, OS = 400 -> w = 1349, gen = 400
for almost the same computational time.

Increasing OFFSPRING_SIZE values performance gets even better:
    * N = 5, OS = 5 -> w = 5, gen = 200
    * N = 10, OS = 9 -> w = 10, gen = 400
    * N = 20, OS = 30 -> w = 24, gen = 400
    * IMPROVED: N = 50, OS = 70 -> w = 72, gen = 400
    * IMPROVED: N = 100, OS = 300 -> w = 166, gen = 800
    * N = 500, OS = 200 -> w = 1328, gen = 1000
for a slower computational time, though (not too much, still pretty feasible!)
</p>

<h1>Comparison with my solution</h1>

<p>
I've made a quite bad algorithm to be honest, it produces a new population and lets it evolve for a fixed number of times. It is definetively slower and capable to solve the problem till N = 20.
I had difficulties to understand this approach and seeing your solution I kinda understood that what gives you a solution in a feasible time isn't the luck to find good individuals among the population (I generated HUUGE populations, let it evolve all NUM_GENERATIONS times, pick the best individuals, generate a new population, let it evolve and so on...) but select the most promising ones, let them produce a potentially good offspring, iterate along the number of generations till an optimal solution is found, etc.

<h1>What you can improve</h1>

<p>
To be honest, I'm not able to say if your method in "let_it_grow" function has weak spots or strong spots in comparison to other potential solution (it is basically how you handled the randomness), it just provides remarkably good results!!! Maybe the idea of removing the highest bloating gene is a very smart one!
A couple things I didn't like:
    * The algorithm is set to solve the problem for only the provided values of N: I tried to put N = 31 for  example and got errors. Anyway, nothing serious ;) 
    * I'd have appreciated comments in most algorithmical parts that would have made your thinking flow much  clearer from the beginning.
Apart from those tiny details, your solution has no issues, as I see.
</p>

<h1>Conclusions</h1>

<p>
As I said before, your algorithm looks gorgeous either for computational time, either for optimization metrics and memory usage, which doesn't grow too much as N increases.

**Comment by CarachinoAlessio** [comment]
Thanks! 😄
